#!/bin/bash

## Description: Run please CLI (of statamic) inside the web container
## Usage: please [flags] [args]
## Example: "ddev please make:user"
## ProjectTypes: laravel
## ExecRaw: true

php ./please "$@"
